[workspace]
authors = ["JackLidge <jacklidgley8@gmail.com>"]
channels = ["conda-forge"]
name = "stonks"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
yfinance = ">=1.4.1,<2"
ipython = ">=9.14.1,<10"
openpyxl = ">=3.1.5,<4"
tqdm = ">=4.68.2,<5"
